### ISSUE TITLE
NotADirectoryError during evaluate the model with "dasg evaluate './exp-swda-longformer-512/checkpointepoch=6.ckpt' --device cuda -b 1 -o exp-swda-longformer-512/results.pkl -v" 

### ISSUE THREAD

**Issue by xiaokebubu** [pzelasko/daseg#6]
Hi, I tried to run model as the "Running the experiments" in readme.md
the model trained successfully and saved the best checkpoint(epoch 6), but when i evaluate on the test set, I got the following error, may I know how to solve it?

Traceback (most recent call last):
  File "/Work/daseg/daseg/models/transformer_model.py", line 34, in from_path
    return TransformerModel.from_pl_checkpoint(model_path, device)
  File "/Work/daseg/daseg/models/transformer_model.py", line 76, in from_pl_checkpoint
    del ckpt['state_dict'][k]
KeyError: 'model.longformer.pooler.dense.weight'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/anaconda3/envs/daseg/bin/dasg", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/Work/daseg/daseg/bin/dasg", line 351, in <module>
    cli()
  File "/home/anaconda3/envs/daseg/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/anaconda3/envs/daseg/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/anaconda3/envs/daseg/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/anaconda3/envs/daseg/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/anaconda3/envs/daseg/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Work/daseg/daseg/bin/dasg", line 73, in evaluate
    model = TransformerModel.from_path(Path(model_path), device=device)
  File "/Work/daseg/daseg/models/transformer_model.py", line 46, in from_path
    **json.load(open(Path(model_path) / 'tokenizer_config.json'))
NotADirectoryError: [Errno 20] Not a directory: 'exp-swda-longformer-512/checkpointepoch=6.ckpt/tokenizer_config.json'

**Comment by pzelasko** [comment]
The actual issue is in the first exception, loading the checkpoint failed. Can you try commenting out the following lines to see if it helps? 

https://github.com/pzelasko/daseg/blob/5e3aaf6e81a44a5eb42226bd376c92c7d1879261/daseg/models/transformer_model.py#L70-L76

**Comment by xiaokebubu** [comment]
Hi, thanks for your quick reply! It now evalute successful, but got a new error when generte the result.pkl file. The exception is as follows:

(daseg) user@dialog:/Work/daseg$ dasg evaluate 'exp-swda-longformer-512/checkpointepoch=6.ckpt' --device cuda -b 1 -o exp-swda-longformer-512/results.pkl -v
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
  - Avoid using `tokenizers` before the fork if possible
  - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
  - Avoid using `tokenizers` before the fork if possible
  - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
  - Avoid using `tokenizers` before the fork if possible
  - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
  - Avoid using `tokenizers` before the fork if possible
  - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Iterating batches: 19it [00:02,  8.65it/s]
SKLEARN_METRICS:
micro_f1  96.58%
macro_f1  60.05%
micro_f1_common_I 96.58%
macro_f1_common_I 60.05%
SEQEVAL_METRICS:
precision 80.84%
recall  78.75%
f1  79.79%
accuracy  96.58%
ZHAO_KAWAHARA_METRICS:
DSER  8.96%
SegmentationWER 12.97%
DER 30.82%
JointWER  36.30%
ORIGINAL_ZHAO_KAWAHARA_METRICS:
DER 17.87%
JointWER  27.40%
macro_f1  60.05%
micro_f1  96.58%
DSER  7.65%
SegmentationWER 14.28%
ARGS:
Traceback (most recent call last):
  File "/home/anaconda3/envs/daseg/bin/dasg", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/Work/daseg/daseg/bin/dasg", line 351, in <module>
    cli()
  File "/home/anaconda3/envs/daseg/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/anaconda3/envs/daseg/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/anaconda3/envs/daseg/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/anaconda3/envs/daseg/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/anaconda3/envs/daseg/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Work/daseg/daseg/bin/dasg", line 93, in evaluate
    slack.write_and_print(f'{key}\t{val:.2%}')
ValueError: Unknown format code '%' for object of type 'str'

**Comment by pzelasko** [comment]
I think it should work if you replace:

```python
slack.write_and_print(f'{key}\t{val:.2%}')
```

with

```python
if isinstance(val, float):
    slack.write_and_print(f'{key}\t{val:.2%}')
else:
    slack.write_and_print(f'{key}\t{val}')
```

in file `/Work/daseg/daseg/bin/dasg`

(I'll try to commit the changes from this thread sometime later)

**Comment by xiaokebubu** [comment]
the code runs well, thanks :)

**Comment by YoussephAhmed** [comment]
Hey I had the same sequence of issues and it now runs successfully after following this thread so I think it's time to push these fixes in a new commit and thank you for your great work :-)

**Comment by pzelasko** [comment]
Right, I’ll find a moment to do the updates. Thanks for the feedback!

**Comment by pzelasko** [comment]
Should be working now, thanks for reporting the issues.
